(R) null
(R) null
(R) null
(R) null
(R) null
(R) null
(R) null
(R) null
(R) null
[0] null null  0 null null null 0.0 []
[1] null null  0 null null null 0.0 []
[2] null null  0 null null null 0.0 []
[3] null null  0 null null null 0.0 []
[4] null null  0 null null null 0.0 []
[5] null null  0 null null null 0.0 []
[6] null null  0 null null null 0.0 []
[7] null null  0 null null null 0.0 []
[8] null null  0 null null null 0.0 []
[9] null null  0 null null null 0.0 []
[10] null null  0 null null null 0.0 []
[11] null null  0 null null null 0.0 []
[12] null null  0 null null null 0.0 []
[13] null null  0 null null null 0.0 []
[14] null null  0 null null null 0.0 []
[15] null null  0 null null null 0.0 []
[16] null null  0 null null null 0.0 []
[17] null null  0 null null null 0.0 []
[18] null null  0 null null null 0.0 []
[19] null null  0 null null null 0.0 []
[20] null null  0 null null null 0.0 []
[21] null null  0 null null null 0.0 []
[22] null null  0 null null null 0.0 []
[23] null null  0 null null null 0.0 []
[24] null null  0 null null null 0.0 []
[25] null null  0 null null null 0.0 []
[26] null null  0 null null null 0.0 []
[27] null null  0 null null null 0.0 []
[28] null null  0 null null null 0.0 []
[29] null null  0 null null null 0.0 []
[30] null null  0 null null null 0.0 []
[31] null null  0 null null null 0.0 []
[32] null null  0 null null null 0.0 []
[33] null null  0 null null null 0.0 []
[34] null null  0 null null null 0.0 []
[35] null null  0 null null null 0.0 []
[36] null null  0 null null null 0.0 []
